version: '3.8'

services:
  postgres:
    image: postgres:latest
    platform: linux/amd64
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ${DATA_PATH}/postgredb:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.40.0
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ACTION_BASE_URL: http://callisto:3030

  callisto:
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - hasura
      - postgres
    ports:
      - "3030:3030"
    env_file:
      - .env
    restart: always
    volumes:
      - ${DATA_PATH}/callisto:/root/.callisto
    deploy:
      replicas: 0 # Set replicas to 0 to prevent automatic startup