version: '3.8'

services:
  postgres:
    image: postgres:latest
    platform: linux/amd64
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./${ROOT_PATH}/postgredb:/var/lib/postgresql/data

#  hasura:
#    image: hasura/graphql-engine:v2.40.0
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#    restart: always
#    environment:
#      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
#      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
#      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
#      # Only for macos or windows
#      ACTION_BASE_URL: http://host.docker.internal:3001
#      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey